install.packages('estimatr', dependencies = T)
install.packages('GGally', dependencies = T)
install.packages('ggplot2', dependencies = T)
install.packages('Hmisc', dependencies = T)
install.packages('performance', dependencies = T)
install.packages('psych', dependencies = T)
install.packages('remotes', dependencies = T)
install.packages('rstudioapi', dependencies = T)
install.packages('rstatix', dependencies = T)
install.packages('summarytools', dependencies = T)
if (!requireNamespace("tinytex", quietly = TRUE)) install.packages("tinytex")
if (Sys.which("xelatex") == "") tinytex::install_tinytex()
