install.packages('fdir', dependencies = T)
install.packages('GGally', dependencies = T)
install.packages('ggplot2', dependencies = T)
install.packages('Hmisc', dependencies = T)
install.packages('performance', dependencies = T)
install.packages('psych', dependencies = T)
install.packages('remotes', dependencies = T)
install.packages('rstatix', dependencies = T)
install.packages('summarytools', dependencies = T)
remotes::install_github("bkeller2/fdir")